/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminVoiceCallsRouteImport } from './routes/admin.voice-calls'
import { Route as ApiPublicAiSendSmsRouteImport } from './routes/api.public.ai.send-sms'
import { Route as ApiPublicAiNextAvailableSlotRouteImport } from './routes/api.public.ai.next-available-slot'
import { Route as ApiPublicAiFindDoctorRouteImport } from './routes/api.public.ai.find-doctor'
import { Route as ApiPublicAiCreatePatientRouteImport } from './routes/api.public.ai.create-patient'
import { Route as ApiPublicAiCheckAvailabilityRouteImport } from './routes/api.public.ai.check-availability'
import { Route as ApiPublicAiCancelAppointmentRouteImport } from './routes/api.public.ai.cancel-appointment'
import { Route as ApiPublicAiBookAppointmentRouteImport } from './routes/api.public.ai.book-appointment'
import { Route as ApiPublicAiLookupAppointmentsRouteImport } from './routes/api.public.ai.lookup-appointments'
import { Route as ApiPublicVapiWebhookRouteImport } from './routes/api.public.vapi.webhook'
const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoiceCallsRoute = AdminVoiceCallsRouteImport.update({
  id: '/voice-calls',
  path: '/voice-calls',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicAiSendSmsRoute = ApiPublicAiSendSmsRouteImport.update({
  id: '/api/public/ai/send-sms',
  path: '/api/public/ai/send-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiLookupAppointmentsRoute =
  ApiPublicAiLookupAppointmentsRouteImport.update({
    id: '/api/public/ai/lookup-appointments',
    path: '/api/public/ai/lookup-appointments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVapiWebhookRoute = ApiPublicVapiWebhookRouteImport.update({
  id: '/api/public/vapi/webhook',
  path: '/api/public/vapi/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiNextAvailableSlotRoute =
  ApiPublicAiNextAvailableSlotRouteImport.update({
    id: '/api/public/ai/next-available-slot',
    path: '/api/public/ai/next-available-slot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiFindDoctorRoute = ApiPublicAiFindDoctorRouteImport.update({
  id: '/api/public/ai/find-doctor',
  path: '/api/public/ai/find-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiCreatePatientRoute =
  ApiPublicAiCreatePatientRouteImport.update({
    id: '/api/public/ai/create-patient',
    path: '/api/public/ai/create-patient',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiCheckAvailabilityRoute =
  ApiPublicAiCheckAvailabilityRouteImport.update({
    id: '/api/public/ai/check-availability',
    path: '/api/public/ai/check-availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiCancelAppointmentRoute =
  ApiPublicAiCancelAppointmentRouteImport.update({
    id: '/api/public/ai/cancel-appointment',
    path: '/api/public/ai/cancel-appointment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiBookAppointmentRoute =
  ApiPublicAiBookAppointmentRouteImport.update({
    id: '/api/public/ai/book-appointment',
    path: '/api/public/ai/book-appointment',
    getParentRoute: () => rootRouteImport,
  } as any)
export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/offline': typeof OfflineRoute
  '/receptionist': typeof ReceptionistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/voice-calls': typeof AdminVoiceCallsRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/ai/book-appointment': typeof ApiPublicAiBookAppointmentRoute
  '/api/public/ai/cancel-appointment': typeof ApiPublicAiCancelAppointmentRoute
  '/api/public/ai/check-availability': typeof ApiPublicAiCheckAvailabilityRoute
  '/api/public/ai/create-patient': typeof ApiPublicAiCreatePatientRoute
  '/api/public/ai/find-doctor': typeof ApiPublicAiFindDoctorRoute
  '/api/public/ai/next-available-slot': typeof ApiPublicAiNextAvailableSlotRoute
  '/api/public/ai/send-sms': typeof ApiPublicAiSendSmsRoute
  '/api/public/ai/lookup-appointments': typeof ApiPublicAiLookupAppointmentsRoute
  '/api/public/vapi/webhook': typeof ApiPublicVapiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/offline': typeof OfflineRoute
  '/receptionist': typeof ReceptionistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/voice-calls': typeof AdminVoiceCallsRoute
  '/api/chat': typeof ApiChatRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/ai/book-appointment': typeof ApiPublicAiBookAppointmentRoute
  '/api/public/ai/cancel-appointment': typeof ApiPublicAiCancelAppointmentRoute
  '/api/public/ai/check-availability': typeof ApiPublicAiCheckAvailabilityRoute
  '/api/public/ai/create-patient': typeof ApiPublicAiCreatePatientRoute
  '/api/public/ai/find-doctor': typeof ApiPublicAiFindDoctorRoute
  '/api/public/ai/next-available-slot': typeof ApiPublicAiNextAvailableSlotRoute
  '/api/public/ai/send-sms': typeof ApiPublicAiSendSmsRoute
  '/api/public/ai/lookup-appointments': typeof ApiPublicAiLookupAppointmentsRoute
  '/api/public/vapi/webhook': typeof ApiPublicVapiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/offline': typeof OfflineRoute
  '/receptionist': typeof ReceptionistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/voice-calls': typeof AdminVoiceCallsRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/ai/book-appointment': typeof ApiPublicAiBookAppointmentRoute
  '/api/public/ai/cancel-appointment': typeof ApiPublicAiCancelAppointmentRoute
  '/api/public/ai/check-availability': typeof ApiPublicAiCheckAvailabilityRoute
  '/api/public/ai/create-patient': typeof ApiPublicAiCreatePatientRoute
  '/api/public/ai/find-doctor': typeof ApiPublicAiFindDoctorRoute
  '/api/public/ai/next-available-slot': typeof ApiPublicAiNextAvailableSlotRoute
  '/api/public/ai/send-sms': typeof ApiPublicAiSendSmsRoute
  '/api/public/ai/lookup-appointments': typeof ApiPublicAiLookupAppointmentsRoute
  '/api/public/vapi/webhook': typeof ApiPublicVapiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/book'
    | '/offline'
    | '/receptionist'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/conversations'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/voice-calls'
    | '/api/chat'
    | '/admin/'
    | '/api/public/ai/book-appointment'
    | '/api/public/ai/cancel-appointment'
    | '/api/public/ai/check-availability'
    | '/api/public/ai/create-patient'
    | '/api/public/ai/find-doctor'
    | '/api/public/ai/next-available-slot'
    | '/api/public/ai/send-sms'
    | '/api/public/ai/lookup-appointments'
    | '/api/public/vapi/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/offline'
    | '/receptionist'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/conversations'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/voice-calls'
    | '/api/chat'
    | '/admin'
    | '/api/public/ai/book-appointment'
    | '/api/public/ai/cancel-appointment'
    | '/api/public/ai/check-availability'
    | '/api/public/ai/create-patient'
    | '/api/public/ai/find-doctor'
    | '/api/public/ai/next-available-slot'
    | '/api/public/ai/send-sms'
    | '/api/public/ai/lookup-appointments'
    | '/api/public/vapi/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/book'
    | '/offline'
    | '/receptionist'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/conversations'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/voice-calls'
    | '/api/chat'
    | '/admin/'
    | '/api/public/ai/book-appointment'
    | '/api/public/ai/cancel-appointment'
    | '/api/public/ai/check-availability'
    | '/api/public/ai/create-patient'
    | '/api/public/ai/find-doctor'
    | '/api/public/ai/next-available-slot'
    | '/api/public/ai/send-sms'
    | '/api/public/ai/lookup-appointments'
    | '/api/public/vapi/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  OfflineRoute: typeof OfflineRoute
  ReceptionistRoute: typeof ReceptionistRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicAiBookAppointmentRoute: typeof ApiPublicAiBookAppointmentRoute
  ApiPublicAiCancelAppointmentRoute: typeof ApiPublicAiCancelAppointmentRoute
  ApiPublicAiCheckAvailabilityRoute: typeof ApiPublicAiCheckAvailabilityRoute
  ApiPublicAiCreatePatientRoute: typeof ApiPublicAiCreatePatientRoute
  ApiPublicAiFindDoctorRoute: typeof ApiPublicAiFindDoctorRoute
  ApiPublicAiNextAvailableSlotRoute: typeof ApiPublicAiNextAvailableSlotRoute
  ApiPublicAiSendSmsRoute: typeof ApiPublicAiSendSmsRoute
  ApiPublicAiLookupAppointmentsRoute: typeof ApiPublicAiLookupAppointmentsRoute
  ApiPublicVapiWebhookRoute: typeof ApiPublicVapiWebhookRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/ai/send-sms': {
      id: '/api/public/ai/send-sms'
      path: '/api/public/ai/send-sms'
      fullPath: '/api/public/ai/send-sms'
      preLoaderRoute: typeof ApiPublicAiSendSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/next-available-slot': {
      id: '/api/public/ai/next-available-slot'
      path: '/api/public/ai/next-available-slot'
      fullPath: '/api/public/ai/next-available-slot'
      preLoaderRoute: typeof ApiPublicAiNextAvailableSlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/find-doctor': {
      id: '/api/public/ai/find-doctor'
      path: '/api/public/ai/find-doctor'
      fullPath: '/api/public/ai/find-doctor'
      preLoaderRoute: typeof ApiPublicAiFindDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/create-patient': {
      id: '/api/public/ai/create-patient'
      path: '/api/public/ai/create-patient'
      fullPath: '/api/public/ai/create-patient'
      preLoaderRoute: typeof ApiPublicAiCreatePatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/check-availability': {
      id: '/api/public/ai/check-availability'
      path: '/api/public/ai/check-availability'
      fullPath: '/api/public/ai/check-availability'
      preLoaderRoute: typeof ApiPublicAiCheckAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/cancel-appointment': {
      id: '/api/public/ai/cancel-appointment'
      path: '/api/public/ai/cancel-appointment'
      fullPath: '/api/public/ai/cancel-appointment'
      preLoaderRoute: typeof ApiPublicAiCancelAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/book-appointment': {
      id: '/api/public/ai/book-appointment'
      path: '/api/public/ai/book-appointment'
      fullPath: '/api/public/ai/book-appointment'
      preLoaderRoute: typeof ApiPublicAiBookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voice-calls': {
      id: '/voice-calls'
      path: '/voice-calls'
      fullPath: '/admin/voice-calls'
      preLoaderRoute: typeof AdminVoiceCallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/ai/lookup-appointments': {
      id: '/api/public/ai/lookup-appointments'
      path: '/api/public/ai/lookup-appointments'
      fullPath: '/api/public/ai/lookup-appointments'
      preLoaderRoute: typeof ApiPublicAiLookupAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vapi/webhook': {
      id: '/api/public/vapi/webhook'
      path: '/api/public/vapi/webhook'
      fullPath: '/api/public/vapi/webhook'
      preLoaderRoute: typeof ApiPublicVapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminVoiceCallsRoute: typeof AdminVoiceCallsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}
const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminVoiceCallsRoute: AdminVoiceCallsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)
const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  OfflineRoute: OfflineRoute,
  ReceptionistRoute: ReceptionistRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicAiBookAppointmentRoute: ApiPublicAiBookAppointmentRoute,
  ApiPublicAiCancelAppointmentRoute: ApiPublicAiCancelAppointmentRoute,
  ApiPublicAiCheckAvailabilityRoute: ApiPublicAiCheckAvailabilityRoute,
  ApiPublicAiCreatePatientRoute: ApiPublicAiCreatePatientRoute,
  ApiPublicAiFindDoctorRoute: ApiPublicAiFindDoctorRoute,
  ApiPublicAiNextAvailableSlotRoute: ApiPublicAiNextAvailableSlotRoute,
  ApiPublicAiSendSmsRoute: ApiPublicAiSendSmsRoute,
  ApiPublicAiLookupAppointmentsRoute: ApiPublicAiLookupAppointmentsRoute,
  ApiPublicVapiWebhookRoute: ApiPublicVapiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
